In [2]:
# Z-Test
import numpy as np
from scipy.stats import norm

In [3]:
sample = [172, 174, 168, 169, 171, 173, 175, 170, 169, 172]
population_mean = 170
population_std = 3
sample_mean = np.mean(sample)
n=len(sample)

In [6]:
z_score = (sample_mean - population_mean)/(population_std/np.sqrt(n))
z_score

np.float64(1.3703203194063098)

In [7]:
p_value = 2 * (1 - norm.cdf(abs(z_score)))

In [8]:
p_value

np.float64(0.17058693287143756)

In [9]:
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis

In [10]:
#T-Test
import numpy as np
from scipy import stats

In [11]:
sample = [172, 174, 168, 169, 171, 173, 175, 170, 169, 172]
sample_mean = np.mean(sample)
sample_std = np.std(sample,ddof = 1)
n = len(sample)
mean_population = 170

In [12]:
t_stats = (sample_mean - mean_population) / (sample_std / np.sqrt(n))
t_stats

np.float64(1.7782469350914734)

In [13]:
p_value = 2 * (1 - stats.t.cdf(abs(t_stats),df = n -1 ))
alpha = 0.05

In [14]:
if p_value < alpha:
    print("reject the null hypothesis")
else:
    print("accept the null hypothesis")

accept the null hypothesis

In [15]:
# Chi - Square Test
import numpy as np
import seaborn as sns
from scipy.stats import chi2_contingency
import pandas as pd

In [16]:
df = sns.load_dataset('titanic')

In [17]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [18]:
contingency_table = pd.crosstab(df['sex'],df['survived'])

In [19]:
contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [20]:
chi2, p_value , dof , expected = chi2_contingency(contingency_table)

In [21]:
expected

array([[193.47474747, 120.52525253],
       [355.52525253, 221.47474747]])

In [22]:
chi2

np.float64(260.71702016732104)

In [23]:
alpha = 0.05

In [24]:
if p_value < alpha:
    print("we reject the null hypothesis and there is a significant relationship between gender and survivl")
else:
    print("there is no connenction")

we reject the null hypothesis and there is a significant relationship between gender and survivl