In [18]:
import pandas as pd
import requests

In [19]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [20]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [21]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,77.2879,9.189,338
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,85.6244,9.146,1155
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,41.5270,8.870,2187
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,16.6243,8.800,381
4,1621552,Facing El Chapo,Two Mexican officers must survive the final ho...,2026-08-21,102.8604,8.800,727

In [22]:
df = pd.DataFrame()

In [23]:
df

Empty DataFrame
Columns: []
Index: []

In [25]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [26]:
df.shape

(8560, 7)

In [27]:
df.to_csv('movies.csv')